import { hlsChangeLevel, hlsInit } from '@lib/hls';
import { PlayerProps } from '@types';
import Hls from 'hls.js';
import { FC, useEffect, useRef } from 'react';

export const Player: FC<PlayerProps> = ({
	ref: videoRefProp,
	hlsRef: hlsRefProp,
	config,
	url = '',
	level = -1,
	onMediaAttaching,
	onMediaAttached,
	onMediaDetaching,
	onMediaDetached,
	onBufferReset,
	onBufferCodecs,
	onBufferCreated,
	onBufferAppending,
	onBufferAppended,
	onBufferEOS,
	onBufferFlushing,
	onBufferFlushed,
	onManifestLoading,
	onManifestLoaded,
	onManifestParsed,
	onLevelSwitching,
	onLevelSwitched,
	onLevelLoading,
	onLevelLoaded,
	onLevelUpdated,
	onLevelPTSUpdated,
	onLevelsUpdated,
	onAudioTracksUpdated,
	onAudioTracksSwitching,
	onAudioTracksSwitched,
	onAudioTrackLoading,
	onAudioTrackLoaded,
	onSubtitleTracksUpdated,
	onSubtitleTracksCleared,
	onSubtitleTrackSwitch,
	onSubtitleTrackLoading,
	onSubtitleTrackLoaded,
	onSubtitleFragProcessed,
	onCuesParsed,
	onNonNativeTextTracksFound,
	onInitPtsFound,
	onFragLoading,
	onFragLoadEmergencyAborted,
	onFragLoaded,
	onFragDecrypted,
	onFragParsingInitSegment,
	onFragParsingUserdata,
	onFragParsingMetadata,
	onFragParsed,
	onFragBuffered,
	onFragChanged,
	onFPSDrop,
	onFPSDropLevelCapping,
	onMaxAutoLevelUpdated,
	onHLSError,
	onDestroying,
	onKeyLoading,
	onKeyLoaded,
	onLiveBackBufferReached,
	onBackBufferReached,
	onSteeringManifestLoaded,
	...rest
}) => {
	const videoRef = useRef<HTMLVideoElement>(null);
	const hlsRef = useRef<Hls | null>(null);

	// biome-ignore lint/correctness/useExhaustiveDependencies: <explanation>
	useEffect(
		() =>
			hlsInit({
				hlsRef: hlsRefProp ?? hlsRef,
				videoRef: videoRefProp ?? videoRef,
				url,
				config,
				onMediaAttaching,
				onMediaAttached,
				onMediaDetaching,
				onMediaDetached,
				onBufferReset,
				onBufferCodecs,
				onBufferCreated,
				onBufferAppending,
				onBufferAppended,
				onBufferEOS,
				onBufferFlushing,
				onBufferFlushed,
				onManifestLoading,
				onManifestLoaded,
				onManifestParsed,
				onLevelSwitching,
				onLevelSwitched,
				onLevelLoading,
				onLevelLoaded,
				onLevelUpdated,
				onLevelPTSUpdated,
				onLevelsUpdated,
				onAudioTracksUpdated,
				onAudioTracksSwitching,
				onAudioTracksSwitched,
				onAudioTrackLoading,
				onAudioTrackLoaded,
				onSubtitleTracksUpdated,
				onSubtitleTracksCleared,
				onSubtitleTrackSwitch,
				onSubtitleTrackLoading,
				onSubtitleTrackLoaded,
				onSubtitleFragProcessed,
				onCuesParsed,
				onNonNativeTextTracksFound,
				onInitPtsFound,
				onFragLoading,
				onFragLoadEmergencyAborted,
				onFragLoaded,
				onFragDecrypted,
				onFragParsingInitSegment,
				onFragParsingUserdata,
				onFragParsingMetadata,
				onFragParsed,
				onFragBuffered,
				onFragChanged,
				onFPSDrop,
				onFPSDropLevelCapping,
				onMaxAutoLevelUpdated,
				onHLSError,
				onDestroying,
				onKeyLoading,
				onKeyLoaded,
				onLiveBackBufferReached,
				onBackBufferReached,
				onSteeringManifestLoaded,
			}),
		[url]
	);

	useEffect(() => hlsChangeLevel(hlsRef, level), [level]);

	return (
		<video
			ref={videoRefProp ?? videoRef}
			style={{
				width: '100%',
				height: '100%',
				aspectRatio: '16 / 9',
				objectFit: 'contain',
				backgroundColor: '#000',
			}}
			playsInline
			{...rest}
		/>
	);
};
